# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'diff-set'
description: 'Github Action for producing lists of files that changed between branches'
author: 'softprops'
env:
  'GITHUB_TOKEN': 'Repository token provided by Github Actions secrets'
runs:
  using: 'node16'
  main: 'dist/index.js'
inputs:
  base:
    description: "Base branch to compare with (defaults to master)"
  unreleased_files:
    description: "File filters to check against unreleased versions"
  newrelease_files:
    description: "File filters to check against for new release files"
  changelog_files:
    description: "File filters to check against the changelist file"
branding:
  color: 'green'
  icon: 'activity'
